using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Player : MonoBehaviour
{

    

    public bool isPlayer1 = true;

    [Header("Movement")]

    public float speed = 20.0f;

    

    public float engineOffVolume = 0.2f;

    public float engineOnVolume = 0.5f;

    

    [Header("Shooting")]

    public GameObject bulletPrefab;
    public Transform bulletSpawn;


    public float fireRate = 0.5f;

    [Header("Sound")]

    public float onVolume = 0.5f;

    public float offVolume = 0.0f;
    
    private AudioSource audioSource;

    

    void Start()
    {
        
        audioSource = GetComponent<AudioSource>();
        InvokeRepeating("Shoot", 0.0f, fireRate);
        
    }

    void Shoot()
    {
        
        Instantiate(bulletPrefab, bulletSpawn.position, transform.rotation);
        
        
    }

    
    void Update()
    {
        var input = new Vector3();
        if(isPlayer1)
        {
            input.x = Input.GetAxis("HorizontalKeys");
            input.z = Input.GetAxis("VerticalKeys");
           
        }
        else
        {
            input.x = Input.GetAxis("HorizontalArrows");
            input.z = Input.GetAxis("VerticalArrows");
        }
        

        transform.position += input * speed * Time.deltaTime;

        if(input != Vector3.zero)
        {
            transform.forward = input;
            audioSource.volume = onVolume;

        }
        else
        {
            audioSource.volume = offVolume;
            
        }
            

    }


}
